name: Basic Workflow

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!"
